# Generated by Django 4.2.9 on 2024-02-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
