# Generated by Django 4.2.9 on 2024-02-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_runs', to='runs.runs')),
            ],
            options={
                'verbose_name_plural': 'AvailableRuns',
            },
        ),
    ]
